### PR TITLE
banner component

### PR DESCRIPTION
**Pull request by vkguru**
Banner component issue #9 
Screen Shot 2020-10-18 at 5 36 49 PM
Screen Shot 2020-10-18 at 5 35 09 PM

### CODE REVIEW

**Comment by Mohamilr** [comment]
i like what i see
Good job boss

**Comment by Kelvinesthy** [comment]
Nice work.. This is nice

**Comment by vkguru** [comment]
> i like what i see
> Good job boss

Thanks Chief

**Comment by vkguru** [comment]
> Nice work.. This is nice

Thanks Chief

**Pull request merged**
