### PR TITLE
Map component

### LINKED ISSUE #10: Build map component
Build map component using the provided design.
Use Google map Api or an alternative api
Write tests: test that the component renders

### PR DESCRIPTION
**Pull request by vkguru**
Kindly review the map component for merge.  This is a pull request to issue #10

Screen Shot 2020-10-14 at 1 23 48 PM

### CODE REVIEW

**Comment by Mohamilr** [comment]
Good job .

Judging by the design, the map has some border-radius. can you please add that.

Also kindly add a Marker to the map indicating any latitude and longitude.

can we also have the zoom in and out plus and minus icons ans indicated in the design?

**Comment by vkguru** [comment]
> Good job .
> 
> Judging by the design, the map has some border-radius. can you please add that.
> 
> Also kindly add a Marker to the map indicating any latitude and longitude.
> 
> can we also have the zoom in and out plus and minus icons ans indicated in the design?

I cannot add a marker now because the marker is suppose to indicate the hospitals in a particular location. As of now, we don't have data for it until we start consuming the API for the data. 

I will work on the border-radius and see what I can do for the plus and minus buttons

**Comment by Mohamilr** [comment]
> > Good job .
> > Judging by the design, the map has some border-radius. can you please add that.
> > Also kindly add a Marker to the map indicating any latitude and longitude.
> > can we also have the zoom in and out plus and minus icons ans indicated in the design?
> 
> I cannot add a marker now because the marker is suppose to indicate the hospitals in a particular location. As of now, we don't have data for it until we start consuming the API for the data.
> 
> I will work on the border-radius and see what I can do for the plus and minus buttons

i know the marker will represent data from the Api. what i said was to add a marker to "indicate ANY location" on the map
just add any latitude and longitude

**Comment by Mohamilr** [comment]
Kindly hide the map api key as well. you can store it in the .env file. 
Ignore the .env file before pushing and give use the key in the Team channel.

**Comment by vkguru** [comment]
> Kindly hide the map api key as well. you can store it in the .env file.
> Ignore the .env file before pushing and give use the key in the Team channel.

Done

**Comment by Mohamilr** [comment]
Hi Victor, a screenshot will be much appreciated. Good job

**Comment by vkguru** [comment]
> > Good job .
> > Judging by the design, the map has some border-radius. can you please add that.
> > Also kindly add a Marker to the map indicating any latitude and longitude.
> > can we also have the zoom in and out plus and minus icons ans indicated in the design?
> 
> I cannot add a marker now because the marker is suppose to indicate the hospitals in a particular location. As of now, we don't have data for it until we start consuming the API for the data.
> 
> I will work on the border-radius and see what I can do for the plus and minus buttons

Done

**Comment by Mohamilr** [comment]
> Hi Victor, a screenshot will be much appreciated. Good job

@vkguru

**Comment by vkguru** [comment]
> > Hi Victor, a screenshot will be much appreciated. Good job
> 
> @vkguru

Screen Shot 2020-10-14 at 11 04 13 PM

**Comment by Mohamilr** [comment]
> > > Hi Victor, a screenshot will be much appreciated. Good job
> > 
> > 
> > @vkguru
> 
> Screen Shot 2020-10-14 at 11 04 13 PM

Good one boss. I am merging

**Review by Mohamilr — APPROVED** [review]

**Comment by vkguru** [comment]
> > > > Hi Victor, a screenshot will be much appreciated. Good job
> > > 
> > > 
> > > @vkguru
> > 
> > 
> > Screen Shot 2020-10-14 at 11 04 13 PM
> 
> Good one boss. I am merging

Okay. Thanks

**Pull request merged**
