### PR TITLE
Ft details page

### LINKED ISSUE #27: Create details page.
this will be the page to be displayed when a location is clicked.

it should have the url = /:the-hospital-name

see the design page.

### PR DESCRIPTION
**Pull request by Mohamilr**

### CODE REVIEW

**Comment by vkguru** [comment]
> _No description provided._

Kindly add a screenshot so that I can see what was done. Thanks

**Comment by Mohamilr** [comment]
> > _No description provided._
> 
> Kindly add a screenshot so that I can see what was done. Thanks

all i did was to create the route and added the footer component. there is nothing to show.
Kindly see the code changes. thanks.

**Comment by Mohamilr** [comment]
image

**Review by vkguru — APPROVED** [review]

**Pull request merged**
