### PR TITLE
[feat]: build search component

### LINKED ISSUE #6: Build search component
Build search component using the provided design.
Write tests: test that the component renders

[RUKAYAT]

### PR DESCRIPTION
**Pull request by Mohamilr**
Please review the code and let me know if it's fine to merge

show 1

show 2

### CODE REVIEW

**Comment by vkguru** [comment]
The border-radius of the search form is too bent. The border-radius on the Figma file is 15px.

On the mobile view, the icons are going out of the border line

**Comment by Mohamilr** [comment]
> The border-radius of the search form is too bent. The border-radius on the Figma file is 15px.
> 
> On the mobile view, the icons are going out of the border line

noted

**Comment by Mohamilr** [comment]
Changes made.


image

image

**Comment by vkguru** [comment]
> Changes made.
> 
> image
> 
> image

Nice. It is fine by me

**Review by vkguru — APPROVED** [review]

**Pull request merged**
